from enum import Enum, auto

class KeywordAbilities(Enum):
    Deathtouch = auto()
    Defender = auto()
    Double_Strike = auto()
    First_Strike = auto()
    Flash = auto()
    Flying = auto()
    Haste = auto()
    Hexproof = auto()
    Indestructible = auto()
    Intimidate = auto()
    Lifelink = auto()
    Menace = auto()
    Protection = auto()
    Prowess = auto()
    Reach = auto()
    Shroud = auto()
    Trample = auto()
    Vigilance = auto()